source 'https://rubygems.org'

gem 'bundler'
gem 'rake'

gem 'rspec'
gem 'rspec-rails'
gem 'shoulda'

gem 'webrat'
gem 'database_cleaner'

gem 'cucumber'
gem 'cucumber-rails',       :require => false

gem 'sqlite3'

gem 'selenium-webdriver',   '~> 2.44.0'
gem 'capybara',             '~> 2.4.4'

gem 'rails',                '~> 4.0.4'

gem 'turbolinks'
gem 'jquery-rails',         '~> 2.3.0'
gem 'bower-rails'
